### ISSUE TITLE
Incorrect Product Name in index.html (Single Shop Box)

### ISSUE THREAD

**Issue by prasxor** [alsiam/web-projects#12]
Issue:
In the `index.html` file, the `h5` title inside the `card-body` div of the single shop box currently displays "Honda Activa 6G". This should be updated to "HARLEY-DAVIDSON - FXSBSE".

File and Code Reference:
`index.html`
<h5 class="card-title">Honda Activa 6G</h5>

suggested correction: The `h5` title should be: `<h5 class="card-title">HARLEY-DAVIDSON - FXSBSE</h5>
`
![image](https://github.com/user-attachments/assets/f7597f11-fc15-4d6e-8fee-16aa424f7e26)

**Comment by Tanmay-coderr** [comment]
Fixed the issue
